### ISSUE TITLE
Integration with dbt tests/projects without a Data Quality intermediary

### ISSUE THREAD

**Issue by emirkmo** [datacontract/datacontract-cli#103]
In a dbt formatted yaml file, one can declare tests on the tables or fields. 
Have you thought about integrating directly with dbt, in order to be compatible with dbt models declared in this way? 

The specifics would be left up to the dbt adapter that is chosen by the user. In this way, you don't even have to integrate directly with a given DBMS, as the adapter takes care of it. You would just have to integrate with dbt & adapters generically.

To be more concrete, the following integrations seem useful (one can always go deeper):

1. **Import**. Import models, schema, and **tests** from a dbt project, schema.yaml, or manifest.json directly. To keep it simple one could configure a `--select` filter like in dbt to only include certain models, creating a data product with a data contract out of the. 
2. **Export**. Export logical models into dbt models, but **include tests** defined in yaml.
3. **Test**. Now that you have "solved" importing and exporting tests and dbt projects, you can run dbt tests using the project configured by the user via the `datacontract` CLI.  

Integrating with test can start as simple as letting the user configure the dbt project/profile via cli arguments, (or even simpler, just the user exporting a proper dbt schema with tests from the data contract and using their dbt project/setup to run it).

Deeper integration would require building in more dbt project parsing or compatibility into the specification itself. I am envisioning grabbing the servers info from the dbt adapter and profile, which itself would be a generic/dbt-specific server object. But this is a lot of work and the more immediate win is just integrating the cli with dbt to extend the current capabilities *especially with respect to respecting/not throwing away tests configured on dbt models via  export/import*.

**Comment by simonharrer** [comment]
Hi, thanks for your detailed idea!

Regarding import: I'm totally for supporting a `datacontract import --format dbt`. I've created #104 for that so we can discuss and track progress there. I'd start to import a dbt yaml file with a model inside as a first start. Interested in contributing? :-)

Regarding export: what do you mean with "include tests defined in yaml". Which tests in which yaml? There are too many different yamls with tests everywhere. :-)

Regarding test: So you are thinking of using dbt as an engine, next to soda-core and great-expectations, to execute the tests. In general, this would work. The Data Contract CLI, however, wants to report results to different integrations. That's why we would need to convert the test results from DBT to the result format of the Data Contract CLI. I'm open to any contribution here.

Hope this helps.

**Comment by emirkmo** [comment]
> Regarding test: So you are thinking of using dbt as an engine, next to soda-core and great-expectations, to execute the tests. In general, this would work.

Next to, or more-likely, instead of.  A fully fledged idea is to add a `dbt-test` Quality Object Type.  and add dbt engine into `engines/dbt` and a dbt test function call same as `check_soda_execute`.

Not sure that fully converting between all possible Quality types, or parallel supporting all of them, is something you want to support? It seems like a huge blocker for adding in more quality types. I envision `dbt-test` quality types are ran by dbt engine, and sodaCL ones are ran by soda, etc.

> Regarding export: what do you mean with "include tests defined in yaml". Which tests in which yaml? There are too many different yamls with tests everywhere. :-)

I meant that once you would import a dbt schema.yaml with tests, the model object would have "tests" in the datacontract.yaml under the models object (as an extension). According to spec, this could additionally (or should only?) go to the Quality object as well https://github.com/datacontract/datacontract-specification?tab=readme-ov-file#quality-object but that requires adding in a dbt-test Quality Object Type

So the quality object should be definable in the same way as dbt tests are, and upon export, for quality objects of type dbt-test, the cli should export them into a dbt schema yaml with tests added to models/columns (for now).

**Comment by jochenchrist** [comment]
There is a related discussion in the specification, if and how quality attributes should be added as first-class citizens in the model section: https://github.com/datacontract/datacontract-specification/issues/55

**Comment by simonharrer** [comment]
@emirkmo we are currently improving support for defining quality checks in the data contract spec https://github.com/datacontract/datacontract-specification/pull/65

**Comment by simonharrer** [comment]
I'm closing this now as it feels stale. Feel free to reopen if you ( @emirkmo ) want to continue this discussion.
