### ISSUE TITLE
datacontract export --format dbml

### ISSUE THREAD

**Issue by jchurel** [datacontract/datacontract-cli#135]
Would be cool to have this export option to have a visual view via [dbdiagram.io ](https://dbdiagram.io/)

dbml == database markup language

**Comment by simonharrer** [comment]
Sure, why not. I don't know what currently has more adoption (mermaid, dbml, plantuml, etc.) but I'm open to any contribution here. :-)

**Comment by jochenchrist** [comment]
I think dbml is a valid choice. Besides dbdiagram.io (proprietary) there are some other tools that support it (e.g., https://github.com/softwaretechnik-berlin/dbml-renderer/)

@jchurel Would you be interested in contributing the export?

**Comment by simonharrer** [comment]
Closing this as #215 implements this. :-)

**Comment by simonharrer** [comment]
@jchurel could you have a look at how the feature was implemented, and whether it solves your use case? Would love to hear your feedback. :-)

**Comment by jchurel** [comment]
@simonharrer of course, how can I make a test?
I've tried `datacontract export --format dbml https://datacontract.com/examples/orders-latest/datacontract.yaml > datacontract.dbml` but have this error:

```
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Invalid value for '--format': 'dbml' is not one of 'jsonschema', 'pydantic-model', 'sodacl', 'dbt', 'dbt-sources',  │
│ 'dbt-staging-sql', 'odcs', 'rdf', 'avro', 'protobuf', 'great-expectations', 'terraform', 'avro-idl', 'sql',         │
│ 'sql-query', 'html', 'go', 'bigquery'.                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯```

**Comment by simonharrer** [comment]
It is not yet released. You need the lastest unreleased dev version. You would need to install it from the source, see the development guide in the README. Or wait until our next release.

**Comment by jchurel** [comment]
I've just tested `python3 cli.py export --format dbml  https://datacontract.com/examples/orders-latest/datacontract.yaml > test.dbml` 

There are errors concerning notes that are too long and are creating a new line: `Invalid newline encountered while parsing` 

You can test the output here to be sure: https://dbdiagram.io/

Except that, once corrected, the dbml looks fine.

**Comment by jpraetorius** [comment]
Happy to – I've been running my gerenrated code through the tool already, as the spec isn't really concise about such things.

**Comment by jpraetorius** [comment]
@jchurel I've been able to reproduce the behavior you describe, but as far as I can tell it is not a specific shortcoming of the implementation but of the way you produce the output.

Redirecting the output using `>` for me (zsh in OSX Terminal) honors the `COLUMNS` Environment variable that Terminal will set to the current width of my Terminal window. That inputs hard linebreaks anywhere the output text is wider than that window. 

All of the following produce correct content according to dbdiagram.io:
* making the terminal window wide and then running the command
* using `COLUMNS=500 python3 ...`
* using the official `--output FILE` switch that directly redirects the contents into a file without the Shell or Terminal interfering.

I feel okay to say: works as expected, just a problem with the environment setup. :)

**Comment by jpraetorius** [comment]
@simonharrer @jochenchrist  – works as expected for me, linebreaks are apparently added by the terminal through the output redirection and are out of our control.

**Comment by jochenchrist** [comment]
@jchurel do you use the Docker version?

There is a known issue and workaround with Dockers line lengths:
https://github.com/datacontract/datacontract-cli/issues/156
