### ISSUE TITLE
Add --output parameter to write to file

### ISSUE THREAD

**Issue by jens-gilion** [datacontract/datacontract-cli#156]
Issue: When piping stdout to a file, and when run inside Docker, there's a line-length-limit of 80 chars (can probably be overriden somehow).

Hence generated HTML tend to break if these extra line-breaks appear in the middle of e.g. css strings.

Suggested solution: Introduce a --output parameter that uses python's file writing to circumvent these environment specific issues.

Impact: Allows generating HTML as a github action, which is a containerized workflow.

**Comment by jochenchrist** [comment]
Thanks for reporting this issue.
Yes, this is a problem with using the docker image.

Workaround
---

You can work around this by using the pip install version or setting the COLUMNS environment variable:

```
docker run --rm -e COLUMNS=100000 -v ${PWD}:/home/datacontract datacontract/cli export --format html https://datacontract.com/examples/orders-latest/datacontract.yaml
```

(Unfortunately this has effects on the datacontract test stdout output as well, so we cannot set it gloablly)

Long term solution
---
Introduce an --output parameter. We'll need it for #155 anyway.
