### ISSUE TITLE
Optional Dependencies

### ISSUE THREAD

**Issue by jens-gilion** [datacontract/datacontract-cli#157]
It would be great if this package would have optional dependencies, for instance I won't use any of the data integrations right now, and installing them takes a lot of time and space (not a massive problem, but not fun awaiting a CI/CD pipeline that should just call `lint` and be done with it).

Further, even if I did need some, I'd only need bigquery, and now the tool spends a bunch of time installing e.g. pyspark.

**Comment by jochenchrist** [comment]
We discussed this before, but currently have no plans to implement it. Also, with current dependency management there is no easy way to add an [all] dependency.

If we get more votes on this issue, we might reconsider,
