### ISSUE TITLE
Extract details from object returned by test()

### ISSUE THREAD

**Issue by john-bunge-ed** [datacontract/datacontract-cli#168]
Hi!

```
data_contract = DataContract(data_contract_file="datacontract.yaml")
run = data_contract.test()
```

I would like to programmatically access the details from the object returned by the `test()` function. In particular, I would like to access all the details about each fail. 

I realize that `run` is a `datacontract.model.run.Run` object. How can I interact with this object?

**Comment by jochenchrist** [comment]
Hi @john-bunge-ed,
have a look at this test:
https://github.com/datacontract/datacontract-cli/blob/f65f0086196f595de8bc27fc6ce56d8fd2584cbd/tests/test_test_parquet.py#L41

For debugging, you can pretty print the results with `run.pretty()` to see all relevant information for each check.

There you have:
- check.result: The result of the individual test
- check.reason: The summary why a test might fail
- check.diagnostics: More details information from the test engine (such as soda-core)

Also, the `run.logs` might be relevant.

**Comment by john-bunge-ed** [comment]
Thank you a lot @jochenchrist

I hope I did not miss a documentation where I could have found an answer myself. In fact, I tried to find some Python function reference for this package, but was not successful.
