### ISSUE TITLE
Inconsistent test result in Databricks when using Spark session (or not)

### ISSUE THREAD

**Issue by john-bunge-ed** [datacontract/datacontract-cli#177]
Thanks for adding the Databricks (programmatic) part to the documentation about servers.

I tested the two server types (Databricks & Databricks programmatic) against each other from a Databricks notebook. In the first case I stored the environment variables for authentication on the cluster. In the second case I used the Spark session (no environment variables stored on the cluster). Tests results however were not the same!

(1)
![image](https://github.com/datacontract/datacontract-cli/assets/159765103/04815b55-21a4-47eb-9553-dfd85c75cc10)
![image](https://github.com/datacontract/datacontract-cli/assets/159765103/3f1e17eb-13ab-4495-af93-8379b772d85c)

(2)
![image](https://github.com/datacontract/datacontract-cli/assets/159765103/4ef93ec0-0e1b-4fbb-8eca-9db5dc5b4051)
![image](https://github.com/datacontract/datacontract-cli/assets/159765103/f865e5b6-5808-4ccb-8c1a-ceb892f235b3)

Thus, when using authentication via spark session, which is obviously preferable over storing credentials as environment variables on the cluster, datacontract-cli accepts a column of type decimal as being double, but this test does not pass when authentication is done via environmental variables.

**Comment by jochenchrist** [comment]
Interesting. What are the defined types of the columns `c_custkey` and `c_acctbal` in your Hive/Unity Data Catalog?

**Comment by john-bunge-ed** [comment]
![image](https://github.com/datacontract/datacontract-cli/assets/159765103/080755a8-f057-460e-8fe9-2f5b0803dd67)

![image](https://github.com/datacontract/datacontract-cli/assets/159765103/23ba4c5a-1925-4ecf-b34b-7cfae05de582)

**Comment by jochenchrist** [comment]
This is a wont-fix as it comes from the soda library that is used to execute the tests.

Workaround is to specify the expected type as a `databricksType` in the `config` options.

https://datacontract.com/#config-object
