### ISSUE TITLE
Enhance Testing Experience with VSCode pytest Integration

### ISSUE THREAD

**Issue by enriquecatala** [datacontract/datacontract-cli#178]
I'd like to propose an enhancement to the project's development environment by adding a VSCode settings file to improve the testing experience for contributors who use VSCode.

Here’s the proposed `.vscode/settings.json`:

```json
{
    // Enable the VSCode pytest extension to enhance the GUI integration for easier test execution and debugging in a TDD environment.
    "python.testing.pytestArgs": [
        "tests"
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true
}
```

**Benefits:**
1. **Enhanced GUI Integration:** By enabling VSCode's pytest extension, contributors can run and debug tests directly from the editor, making it more straightforward to use and navigate.
2. **Focus on pytest:** Since the project utilizes pytest for testing, setting `python.testing.pytestEnabled` to true while disabling `unittest` support helps avoid any confusion and streamlines the development process.
3. **Ease of Use:** This addition would lower the entry barrier for new contributors and improve productivity and efficiency for existing contributors by reducing the setup steps for a fully functional development environment in VSCode.

Incorporating this change could significantly enhance the developer experience, particularly for those adopting a test-driven development (TDD) approach. I believe this would be a valuable update to our workflow and encourage more robust testing practices.

Looking forward to your thoughts on this proposal.

**Comment by jochenchrist** [comment]
Following the data-driven decision in #179, let's look at some other projects:

To move forward towards a decision here, I looked at some random popular python projects on Github:

https://github.com/apache/airflow
https://github.com/spotify/luigi
https://github.com/sqlalchemy/sqlalchemy
https://github.com/sodadata/soda-core
https://github.com/great-expectations/great_expectations
https://github.com/tiangolo/fastapi
https://github.com/yaml/pyyaml
https://github.com/psf/requests

None of them added a `.vscode` or `.idea` folder to their repository, I would also follow this approach.

Again, I am not keen to do so, but I would rather reject this issue, to keep the code base simple. Sorry.
