### ISSUE TITLE
Propose Adding a Conda Environment File for Improved Development Setup

### ISSUE THREAD

**Issue by enriquecatala** [datacontract/datacontract-cli#179]
I'd like to suggest an enhancement to our project’s setup process by introducing a `conda_environment.yml` file. This file will facilitate a smoother and more consistent environment setup for contributors, especially those using Conda.

Here’s the proposed `conda_environment.yml`:

```yaml
name: datacontract-cli
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - pytest
    - ruff
    - -e '.[dev]'
```

**Benefits:**

1. **Integration with Development Tools:** Conda environments can be easily integrated with IDEs and other development tools, like `vscode`, enhancing productivity and ensuring that developers work within environments that mirror production setups.

1. **Consistent Environment Across Platforms:** A Conda environment ensures that all contributors are working with the same dependencies, which minimizes "works on my machine" problems.

1. **Streamlined Setup Process:** New contributors can get up and running with a single command, enhancing their initial experience and reducing barriers to entry.

1. **Python Version Management:** Conda allows you to specify, install, and manage multiple versions of Python. This is crucial for projects that need to maintain compatibility with specific Python versions or need to test across multiple versions.

2. **Easy Environment Switching:** Conda facilitates easy switching between project environments. This feature is invaluable for developers working on multiple projects with different dependencies, as it ensures that these dependencies don’t conflict with each other.

4. **Platform Agnostic:** Conda works across all major operating systems (Linux, macOS, and Windows), ensuring consistent environment setup across different development platforms.

5. **Dependency Management:** Conda automatically handles package dependencies and environment management. It resolves dependencies and installs the correct versions of packages and their dependencies to prevent conflicts.

7. **Environment Replication:** Conda makes it easy to replicate environments across different machines or for different team members, using simple commands (`conda env export` and `conda env create` from a `.yml` file). This feature ensures consistency and reproducibility in collaborative projects.

I believe that adding this file will not only simplify the development setup but also align with our goals of maintaining high standards of code quality and reliability. Let me know your thoughts on this and if there are any adjustments you'd suggest.

Thank you for considering this addition to our project.

**Comment by jochenchrist** [comment]
I understand the benefits.
However, I'm a little cautious here because I'm not a Conda user and we can't take on long-term maintenance for this.

There is also the risk of conflicts with venv and of course the additional complexity.

The same, of course, applies to other alternatives such as pipenv, poetry, virtualenv, ...

Any other opinions?

**Comment by enriquecatala** [comment]
Thank you for considering the implications of this. In regards of risks and conflicts I wanted to point:

- Simplified Environment Setup: With Conda, setting up a development environment is as straightforward as running conda env create -f environment.yml. This ensures that all developers, regardless of their operating system, have a consistent environment, including the exact version of Python and all dependencies.
- Version Management: As you noted, our README specifies Python 3.11 and mentions the availability of Python 3.12 as a pre-release for 0.9.3. Conda excels in managing multiple Python versions across different environments without conflicts, something that can be more cumbersome with venv.
- Isolation from System Python: Unlike venv, which uses the system Python, Conda environments are completely isolated, which reduces the risk of system-wide conflicts and ensures that installations of critical packages don't affect other software on the system.
- Flexibility: Developers can still choose to use venv or other tools if they prefer. Conda does not override or interfere with venv when properly managed. It simply provides an additional, robust option for those who need it.

My point here is that while introducing Conda might seem to add complexity, the initial effort could reduce ongoing maintenance needs by preventing environment discrepancies and dependency issues among team members.

**Comment by simonharrer** [comment]
My suggestion:
- venv as the primary (supported) way of developing the cli
- conda is offered as an alternative (unsupported) for those who like to use that

**Comment by jochenchrist** [comment]
To move forward towards a decision here, I looked at some random popular python projects on Github:

https://github.com/apache/airflow
https://github.com/spotify/luigi
https://github.com/sqlalchemy/sqlalchemy
https://github.com/sodadata/soda-core
https://github.com/great-expectations/great_expectations
https://github.com/tiangolo/fastapi
https://github.com/yaml/pyyaml
https://github.com/psf/requests

None of them added an environment.yml to their repository.


When looking a bit further, to data science projects in particular, these repos have a Conda environment.yml

https://github.com/numpy/numpy
https://github.com/pandas-dev/pandas

Conda seems to be popular only in data science projects.


Summary:
I am not keen to do so, but I would rather reject this issue, to keep the code base simple.
