### ISSUE TITLE
Export data to MonteCarlo

### ISSUE THREAD

**Issue by pixie79** [datacontract/datacontract-cli#184]
It would be great to see the soda checks also extended to support other systems like MC

https://docs.getmontecarlo.com/docs/monte-carlo-api-1

**Comment by jochenchrist** [comment]
For this, we need to define a generic Data Contract DSL first: https://github.com/datacontract/datacontract-specification/issues/55

**Comment by simonharrer** [comment]
Please reopen if someone wants to have a go at this.
