### ISSUE TITLE
Export Data Assets to Atlan

### ISSUE THREAD

**Issue by pixie79** [datacontract/datacontract-cli#185]
Can the tool export models to data governance tooling like Atlan?

Especially tagging of entities and classifications as that would allow for a great overview of data rules.

https://developer.atlan.com/models/api/

**Comment by jochenchrist** [comment]
Absolutely. 
Our vision is the data contracts is the source for publishing meta data to all relevant data catalog and governance tools (Atlan, DataHub, Data Mesh Manager, Collibra, Glue, Unity Catalog, Purview).

**Comment by jochenchrist** [comment]
I am going to close this ticket, as there will be no priority in the next weeks. Unity Catalog will have priority from my side.
If someone wants to contribute Atlan support, feel free to reopen this issue.

**Comment by nicor88** [comment]
@jochenchrist we are interested in this feature - any guidelines that could allow us to start contributing to this feature? Thanks
