### ISSUE TITLE
Export model to class definition

### ISSUE THREAD

**Issue by pixie79** [datacontract/datacontract-cli#187]
It would be great to be able to export the model definition to different language definitions.

Eg. Python Class & Go Structs

**Comment by jochenchrist** [comment]
Code generation, including generating classes, such a Python, Java, Go, ... from the model is the idea of the export feature.

For Python, there is support to export to Pydantic classes

```
datacontract export --format pydantic-model  https://datacontract.com/examples/orders-latest/datacontract.yaml
```

We are open to supporting more languages based on use-cases, needs and contributions.
