### ISSUE TITLE
Support for MS Sqlserver 

### ISSUE THREAD

**Issue by RobertLD** [datacontract/datacontract-cli#196]
Our company is actively pursuing stricter guarantees on cross-team data via the data contract-cli. We currently make use of MS SqlServer and would like to know if this is supported within the data contract cli?

**Comment by jochenchrist** [comment]
Currently, it is not implemented, but should not be too difficult to implement, as soda-core supports ms sqlserver.

As a precondition, we'd need to add sqlserver to the server specification
https://github.com/datacontract/datacontract-specification/?tab=readme-ov-file#server-object

**Comment by jochenchrist** [comment]
Would you (or your team) have some capacity to contribute a Pull-Request?

**Comment by RobertLD** [comment]
I'm sure I can find some time to  pull the code and investigate, hopefully sometime this week or next.

**Comment by jochenchrist** [comment]
Added `sqlserver` to data contract specification: https://github.com/datacontract/datacontract-specification/?tab=readme-ov-file#sql-server-server-object

**Comment by RobertLD** [comment]
> Added `sqlserver` to data contract specification: https://github.com/datacontract/datacontract-specification/?tab=readme-ov-file#sql-server-server-object

Including the supporting code, or just preparing the doc?

**Comment by simonharrer** [comment]
Jochen added the server type to the specification.

What is now missing is adding support in the CLI within the python code base. Do you want to have a try for this @RobertLD ? It should be straight forward mapping to soda sqlserver type.

**Comment by RobertLD** [comment]
I'll take a crack at it once I get my bearings

**Comment by RobertLD** [comment]
> Added `sqlserver` to data contract specification: https://github.com/datacontract/datacontract-specification/?tab=readme-ov-file#sql-server-server-object



> Jochen added the server type to the specification.
> 
> What is now missing is adding support in the CLI within the python code base. Do you want to have a try for this @RobertLD ? It should be straight forward mapping to soda sqlserver type.

I've published a rough PR for the changes because the specification published earlier for SQLServer doesn't match exactly what I would expect (namely missing the driver, etc.)

With some guidance or an update of the spec I can continue work on it
https://github.com/datacontract/datacontract-cli/pull/204


ty

**Comment by RobertLD** [comment]
Completed in PR #204
