### ISSUE TITLE
datacontract export --format html datacontract.yaml > orders.html  in genrated html file servicelevels and examples information is not present even if its there in yaml data contracts

### ISSUE THREAD

**Issue by rushi2411** [datacontract/datacontract-cli#205]

**Comment by jochenchrist** [comment]
Thanks for reporing. 
This issue has been resovled with #203 and will be available with next version v0.10.4

**Comment by rushi2411** [comment]
I am executing datacontract export --format html datacontract.yaml > orders.html command its generating orders.html file but it dose not contain service levels information in it. yamal file is correct and have service levels info in it

**Comment by jochenchrist** [comment]
v0.10.4 has been released.
Hope this works now :)
