### ISSUE TITLE
Add support for GCS Server objects

### ISSUE THREAD

**Issue by hcrosse** [datacontract/datacontract-cli#231]
Create a GCS server object similar to the [S3 one](https://github.com/datacontract/datacontract-specification?tab=readme-ov-file#s3-server-object).

It's possible this is unnecessary due to [GCS's S3 interoperability](https://cloud.google.com/storage/docs/interoperability), in which case my ask changes to an update to the documentation to make this use explicitly stated (which I'll copy over to the [specification repo](https://github.com/datacontract/datacontract-specification)) in the README.

**Comment by jochenchrist** [comment]
Let's stick with the s3 config option (and its `endpointUrl` option) and add a documentation for GCS, Azure Blob Storage, ... otherwise we will come with an explosion of similar file storage configs.

**Comment by hcrosse** [comment]
It looks like there's already an [Azure block](https://github.com/datacontract/datacontract-cli?tab=readme-ov-file#azure) so if the rest of the CLI already supports GCS using the S3 endpoint we just need to add this

**Comment by jochenchrist** [comment]
OK, let's add explicit support for server type `gcs`.

**Comment by hcrosse** [comment]
Closed by https://github.com/datacontract/datacontract-cli/commit/17b291299b6df59b34963d299f0299913de7419a
