### ISSUE TITLE
Add pre-commit hook for formatting/linting

### ISSUE THREAD

**Issue by RobertLD** [datacontract/datacontract-cli#241]
Formatting is imo something that should just happen automatically. While working on this, I found myself forgetting to run the ruff command and it would be much easier with something like the pre-commit package installed.

Just a dev QoL feature; I also think it would be good to tag as "good first issue" since it's a super easy and low impact change.

**Comment by jochenchrist** [comment]
I'd agree

**Comment by jochenchrist** [comment]
I think this pre-commit hook would be fine:

https://github.com/astral-sh/ruff-pre-commit

**Comment by jochenchrist** [comment]
Done
