### ISSUE TITLE
Azure blob wildcard path not working

### ISSUE THREAD

**Issue by JonPipple** [datacontract/datacontract-cli#257]
Hi, Documentation shows that a path with wildcard should work:
![image](https://github.com/datacontract/datacontract-cli/assets/91060557/c2c2725e-2107-4017-93bd-c606cbc0b1bb)

However I get the following error: 
![image](https://github.com/datacontract/datacontract-cli/assets/91060557/21c0244b-71aa-4977-bfda-d4eeee6ff923)

When I use the path of one specific .json file it does work but still shows "Server type azure not supported"

**Comment by jochenchrist** [comment]
1)
The message "Server type azure not supported" warning refers to an additional JSON-Schema check that translates the data contract model to a JSON schema and makes a schema validation. This is currently not implemented for azure.
https://github.com/datacontract/datacontract-cli/blob/main/datacontract/engines/fastjsonschema/check_jsonschema.py#L154

A pull request would be appreciated if you have some capacity.

**Comment by JonPipple** [comment]
Thanks for the quick responses! 

This is the full output that I get:
![image](https://github.com/datacontract/datacontract-cli/assets/91060557/e1ed7cee-1609-4e99-9a21-65bd34c36b73)

Server definition is as follow:
![image](https://github.com/datacontract/datacontract-cli/assets/91060557/a321c36f-d18c-48d4-b822-4600fa7cab3a)

**Comment by jochenchrist** [comment]
In your model (!), you use the field "data_type" for `adm_nr`.
Can you try with renaming the field it to `type`.

**Comment by JonPipple** [comment]
Done, but get exactly the same error output

**Comment by jochenchrist** [comment]
Regarding "type must be string, but is number"

Hmm, now it is a different error message (type must be string, but is number).
The errors comes from DuckDb while reading the JSON files. My current thesis is that the JSON files are inconsistent? Hard to debug without access to files.

Could you invest in debugging by trying to read the files directly in a Python Notebook using DuckDB https://duckdb.org/docs/data/json/overview.html

**Comment by jochenchrist** [comment]
Closing issue as stale.
