### ISSUE TITLE
DuckDB native Deltalake

### ISSUE THREAD

**Issue by jochenchrist** [datacontract/datacontract-cli#258]
DuckDB now has native Deltalake support:
https://duckdb.org/2024/06/10/delta

This can replace the current PyArrow implementation and we can save a few hundres MBs of dependencies.

Repository: https://github.com/duckdb/duckdb_delta

**Comment by GetLouied** [comment]
@jochenchrist 

If you haven't started working on this yet, I would like to take a crack at it.

**Comment by jochenchrist** [comment]
I have not started any work here

**Comment by jochenchrist** [comment]
Issue is blocked by https://github.com/duckdb/duckdb_delta/issues/14

**Comment by jochenchrist** [comment]
Has been fixed in duckdb extension https://github.com/duckdb/duckdb_delta/pull/49
