### ISSUE TITLE
Reg: Trino integration

### ISSUE THREAD

**Issue by bazooka720** [datacontract/datacontract-cli#264]
We plan to use it as a library vs CLI and wondering if you offer support for Trino? Something thet will connect to Trino REST API? We have some views and tables populated by those queries (we have RBAC established and so all connections to trio needs specific user params)

**Comment by stefannegele** [comment]
Hi @bazooka720, thanks for the issue. Can you please add some more information on the specific user params you need?

**Comment by bazooka720** [comment]
subdomain/url/cluster
username of user making query
password of user making query
query string
catalog and schema might be sent as independant variables, if not trino will extract them from the query (optional)

**Comment by jochenchrist** [comment]
Let's discuss the required new server properties for the Data Contract Specification.

Proposal:

```
servers:
  production:
    type: trino
    host: 127.0.0.1
    port: 5432
    catalog: hive
    schema: my_schema
```

For connecting with the CLI, the credentials would be ENV variables, like these:

```
DATACONTRACT_TRINO_USERNAME=username
DATACONTRACT_TRINO_PASSWORD=password
```

The query will be composed in datacontract cli that executes the tests.

Any important things missing here?

**Comment by bazooka720** [comment]
What if we do via the library?

**Comment by jochenchrist** [comment]
This would also apply for the Python library. You have the server details in the contract and read credentials from ENV variables.

**Comment by stefannegele** [comment]
Quick update:

I drafted PRs for the spec and for the CLI to support trino. Unfortunatly, I still have an issue in the unit test and don't have time to address it until next week.

https://github.com/datacontract/datacontract-specification/pull/73
https://github.com/datacontract/datacontract-cli/pull/278

**Comment by bazooka720** [comment]
Is it planned to be merged soon?

**Comment by stefannegele** [comment]
I expect to finish it this week

**Comment by stefannegele** [comment]
This is merge, thanks @jochenchrist for reviewing!
