### ISSUE TITLE
Can't import valid jsonschema

### ISSUE THREAD

**Issue by Plozano94** [datacontract/datacontract-cli#300]
Hi there,
I'm just starting to test the tool and found tha I couldn't import a basic json schema.

**Reproduce**:
Create jsonschemafile.json with 
`{
    "$id": "https://example.com/person.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Person",
    "type": "object",
    "properties": {
      "firstName": {
        "type": "string",
        "description": "The person's first name."
      },
      "lastName": {
        "type": "string",
        "description": "The person's last name."
      },
      "age": {
        "description": "Age in years which must be equal to or greater than zero.",
        "type": "integer",
        "minimum": 0
      }
    }
}
`
and then
datacontract import --format jsonschema --source jsonschemafile.json

**Error**:
![imagen](https://github.com/datacontract/datacontract-cli/assets/10929376/6287f7bc-10da-4cf2-a0b0-21c21bd2098f)

**Comment by jochenchrist** [comment]
Confirming this bug, when the `description` field on top level is missing.

Workaround: Define a description field

```
{
    "$id": "https://example.com/person.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Person",
    "type": "object",
    "description": "Some description",
    "properties": {
        "firstName": {
            "type": "string",
            "description": "The person's first name."
        },
        "lastName": {
            "type": "string",
            "description": "The person's last name."
        },
        "age": {
            "description": "Age in years which must be equal to or greater than zero.",
            "type": "integer",
            "minimum": 0
        }
    }
}
```

**Comment by jochenchrist** [comment]
Fix is scheduled for `v0.10.9`

**Comment by Plozano94** [comment]
Thank you!

**Comment by jochenchrist** [comment]
v0.10.9 has been released
