### ISSUE TITLE
JsonSchema importer doesn't support array types

### ISSUE THREAD

**Issue by Plozano94** [datacontract/datacontract-cli#305]
Hi there,
trying JsonSchema importer seems to fail when a property item is an array. In order to test try:

**Schema**:
myjsonschema.json

`{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "eventId": {
      "type": "string"
    },
    "eventName": {
      "type": "string"
    },
    "eventCreationDate": {
      "type": "integer"
    },
    "collections": {
      "type": "array",
      "items": [
        {
          "type": "integer"
        }
      ]
    }
  },
  "required": [
    "eventId",
    "eventName",
    "eventCreationDate",
    "collections"
  ]
}
`
**Command**: "datacontract import --format jsonschema --source myjsonschema.json"

**Error:**
![imagen](https://github.com/datacontract/datacontract-cli/assets/10929376/b5e50a76-4e1d-41e4-bdc7-8eaf81d0b0b8)

**Comment by RobertLD** [comment]
I can replicate this, let me dig into it a bit more

**Comment by jochenchrist** [comment]
Implemented, target with release `v0.10.11`
