### ISSUE TITLE
Pyspark dependency is required despite marked as optional

### ISSUE THREAD

**Issue by janhicken** [datacontract/datacontract-cli#312]
The `pyspark` dependency has been changed to an optional dependency, installed using either the `databricks` or `kafka` extra.

However, the [`data_contract` module](/datacontract/datacontract-cli/blob/v0.10.9/datacontract/data_contract.py#L7) imports `pyspark` explicitly. This will fail when `pyspark` is not installed:

```
data_contract.py:7: in <module>
    from pyspark.sql import SparkSession
E   ModuleNotFoundError: No module named 'pyspark'
```

As the `SparkSession` imported is used for type-checking only, maybe this can be fixed easily.

Furthermore, the same issue can be found in the [`check_soda_execute` module](/datacontract/datacontract-cli/blob/v0.10.9/datacontract/engines/soda/check_soda_execute.py#L3).

**Comment by RobertLD** [comment]
https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING

This looks to be the accepted solution to problems like this; but it's not very elegant. I can put a fix up within a few days but if someone else wants to go ahead; should only be a couple minutes.

**Comment by RobertLD** [comment]
Opened a pull request for this using the suggested solution via the Typing module

**Comment by jochenchrist** [comment]
PR merged.

**Comment by RobertLD** [comment]
> PR merged.

That PR had an issue that caused CI/CD to fail. Please see the follow up 
https://github.com/datacontract/datacontract-cli/pull/320


Sorry about that again
