### ISSUE TITLE
Application install installs every available package version for moto

### ISSUE THREAD

**Issue by RobertLD** [datacontract/datacontract-cli#321]
While installing dependencies for the datacontract-cli, the application will iterate through all available versions of the moto package. This can slow down CI/CD builds and lower general usability

![image](https://github.com/datacontract/datacontract-cli/assets/30250210/f4fcc7a1-2b65-465e-877d-abd56b66d203)

**Comment by jochenchrist** [comment]
Thanks for reporting.
