### ISSUE TITLE
Glue: `map` data type is not supported

### ISSUE THREAD

**Issue by roykoand** [datacontract/datacontract-cli#334]
`datacontract import --format glue` on a Glue table with a column that has `map` data type returns `type: variant`.
I think this happens because `map` is not supported in this function:
https://github.com/datacontract/datacontract-cli/blob/37cf8dc8711367010dd020379bee3920346f1507/datacontract/imports/glue_importer.py#L237

**Comment by jochenchrist** [comment]
Also see discussion here: https://github.com/datacontract/datacontract-specification/pull/61 and here https://github.com/datacontract/datacontract-specification/issues/80

**Comment by roykoand** [comment]
Ah, thank you @jochenchrist!

**Comment by jochenchrist** [comment]
Implemented, and targeted with `v0.10.11`

**Comment by roykoand** [comment]
Thank you @jochenchrist!!!
