### ISSUE TITLE
Delta table support for server type local is not implemented yet, it only checks for azure  and then directly goes to AWS s3 

### ISSUE THREAD

**Issue by Happycipher** [datacontract/datacontract-cli#338]
I think the control flow does this in line number 52 of https://github.com/datacontract/datacontract-cli/blob/main/datacontract%2Fengines%2Fsoda%2Fconnections%2Fduckdb.py

**Comment by jochenchrist** [comment]
Yes, correct. Should also support local.

If you have the ability and time to create a pull request, we're always happy to accept contributions.
