### ISSUE TITLE
`bigquery` table filtering is not working?

### ISSUE THREAD

**Issue by roykoand** [datacontract/datacontract-cli#358]
I don't have an access to any BigQuery table in my pocket but I am almost sure `bigquery` table filtering does not work because of this line:
https://github.com/datacontract/datacontract-cli/blob/ee32b102eea279d1da420eb377dd0c99fb8a24fb/datacontract/imports/bigquery_importer.py#L19

It should be:
```
 import_args.get("bigquery_table"), 
```

As it's the parameter passed in CLI:
https://github.com/datacontract/datacontract-cli/blob/ee32b102eea279d1da420eb377dd0c99fb8a24fb/datacontract/cli.py#L220

This is similar to an issue we had with `glue_table` (https://github.com/datacontract/datacontract-cli/issues/333)

**Comment by jochenchrist** [comment]
duplicates #377
