### ISSUE TITLE
Optional dependencies are actually required

### ISSUE THREAD

**Issue by janhicken** [datacontract/datacontract-cli#360]
I've just updated the `datacontract-cli` in my project from `0.10.6` to `0.10.10`.

The update causes some dependencies to be removed, as they've been moved to optional extras.

However, running Soda checks against a PostgreSQL database still causes issues similar to #312:

```
venv/lib/python3.11/site-packages/datacontract/data_contract.py:16: in <module>
    from datacontract.engines.soda.check_soda_execute import check_soda_execute
venv/lib/python3.11/site-packages/datacontract/engines/soda/check_soda_execute.py:11: in <module>
    from datacontract.engines.soda.connections.duckdb import get_duckdb_connection
venv/lib/python3.11/site-packages/datacontract/engines/soda/connections/duckdb.py:3: in <module>
    from deltalake import DeltaTable
E   ModuleNotFoundError: No module named 'deltalake'
```

And, after installing `deltalake`, we're back to the `pyspark` problem of #312:

```
venv/lib/python3.11/site-packages/datacontract/data_contract.py:16: in <module>
    from datacontract.engines.soda.check_soda_execute import check_soda_execute
venv/lib/python3.11/site-packages/datacontract/engines/soda/check_soda_execute.py:12: in <module>
    from datacontract.engines.soda.connections.kafka import create_spark_session, read_kafka_topic
venv/lib/python3.11/site-packages/datacontract/engines/soda/connections/kafka.py:3: in <module>
    from pyspark.sql import SparkSession
E   ModuleNotFoundError: No module named 'pyspark'
```

I think the imports need to be moved inside the `if` branches in `check_soda_execute()` dependening on the `server.type` chosen.

**Comment by jochenchrist** [comment]
Agree, the `import DeltaTable` should be conditional.

Workaround is to install all extras:

```
pip install datacontract-cli[all]
```

**Comment by HenkvanDyk** [comment]
Is there a long term fix for this in the backlog?

**Comment by jochenchrist** [comment]
Solution would be to make the DeltaTable import conditional like this pattern:

```
if typing.TYPE_CHECKING:
    from pyspark.sql import SparkSession
```

Would you have some time and ability to work on a pull request?

**Comment by jochenchrist** [comment]
Fixed with https://github.com/datacontract/datacontract-cli/pull/370

(Targeted with v0.10.12)
