### ISSUE TITLE
How to pass server, catalog and schema when creation the Datacontract [Databricks]

### ISSUE THREAD

**Issue by letnotimitateothers** [datacontract/datacontract-cli#369]
Hello,

Thanks again for this useful tool 👍🏾 

I'm using these commands to test my data contract :

![Screen Shot 2024-08-09 at 16 16 22](https://github.com/user-attachments/assets/11a47798-0263-4532-96a9-98697dbfe520)

Here are the servers configuration in the datacontract.yaml file:

![Screen Shot 2024-08-09 at 16 18 14](https://github.com/user-attachments/assets/e04f8263-cc06-4055-a94b-bf88f605d80a)

I want to pass a new server as a parameter to the Datacontract() function, with it's own catalog and schema and host.

How can I do that ?

Thanks a lot for your answer.

Amélie Medem.

**Comment by jochenchrist** [comment]
If you have to change the server settings, you can use the resolve method to read the data contract specification, change it, and inject it as data_contract parameter.


```
data_contract_file = "fixtures/lint/datacontract_unknown_model.yaml"
data_contract_specification = resolve.resolve_data_contract_from_location(data_contract_file)
// change the server settings
data_contract = DataContract(data_contract=data_contract_specificaction)
```

**Comment by letnotimitateothers** [comment]
Thanks a lot, Jochen :)
That solved my problem.
Amelie.
