### ISSUE TITLE
Export format for diff/breaking

### ISSUE THREAD

**Issue by pierre-monnet** [datacontract/datacontract-cli#418]
What do you think about adding an export format to diff/breaking, or adding a diff/breaking mode to export?

I find that exporting to SQL is a good feature, but it only allows you to export the **CREATE** table, it would be nice to be able to generate the **UPDATE** table commands that correspond to the difference between 2 versions of datacontract.

I've generated this kind of function in my project, and I think it might be of interest to others.

**Comment by jochenchrist** [comment]
Could you sketch an example of an input, command and the expected output?

**Comment by pierre-monnet** [comment]
Hi, 
It should be something like 
`datacontract diff datacontract-v1.yaml datacontract-v2.yaml --format SQL`
This command return ALTER TABLE queries like 
`ALTER TABLE database.table ALTER COLUMN column1 COMMENT 'my comment'
ALTER TABLE database.table ALTER COLUMN column2 COMMENT 'my comment 2' TYPE INTEGER
ALTER TABLE database.table ADD COLUMN column6 COMMENT 'my comment 3' TYPE STRING`

**Comment by jochenchrist** [comment]
Closing this ticket as wontfix.

**Comment by pierre-monnet** [comment]
Hi,
I understand the complexity to do that with sql diff, but maybe it's possible to reuse Breaking Changes generated by diff command and convert them to ALTER TABLE queries.

Given the following exemple:
```
❯ datacontract diff datacontract-fields-v1.yaml datacontract-fields-v2.yaml
4 changes: 1 error, 0 warning, 3 info
info    [field_added] at datacontract-fields-v2.yaml
        in models.my_table.fields.field4
            added the field

info    [field_description_added] at datacontract-fields-v2.yaml
        in models.my_table.fields.field1.description
            added with value: `desc_added`

info    [field_description_updated] at datacontract-fields-v2.yaml
        in models.my_table.fields.field2.description
            changed from `old_desc` to `new_desc`

error   [field_type_updated] at datacontract-fields-v2.yaml
        in models.my_table.fields.field3.type
            changed from `string` to `boolean`
```

Then converter result should be
```
❯ datacontract diff datacontract-v1.yaml datacontract-v2.yaml --format SQL
4 changes: 1 error, 0 warning, 3 info
-- info
ALTER TABLE my_table ADD COLUMN field4 TYPE string

-- info
ALTER TABLE my_table ALTER COLUMN field1 COMMENT 'desc_added'

-- info
ALTER TABLE my_table ALTER COLUMN field2 COMMENT 'new_desc'

-- error
ALTER TABLE my_table ALTER COLUMN field2 TYPE boolean
```
