### ISSUE TITLE
Datacontract model raises invalid exception type

### ISSUE THREAD

**Issue by RobertLD** [datacontract/datacontract-cli#471]
```
Traceback (most recent call last):
  File "/home/rderienzo/.local/lib/python3.11/site-packages/datacontract/model/data_contract_specification.py", line 231, in from_file
    raise (f"The file '{file}' does not exist.")
TypeError: exceptions must derive from BaseException
```

as a result of trying to programmatically create a datacontract from a bytes-like object
```
x = pl.Dataframe()
c = DataContract.init()
c.from_file(x.serialize())
```

**Comment by stefannegele** [comment]
Hi @RobertLD,
thanks for raising the issue. I just fixed the problem with the invalid exception. Looking at your code I'm wondering what you're trying to achieve. Is it possible that you're looking for somthing like:

```python
```
