### ISSUE TITLE
Add support for TIMESTAMP type in duckdb

### ISSUE THREAD

**Issue by RobertLD** [datacontract/datacontract-cli#472]
https://github.com/datacontract/datacontract-cli/blob/988a4c88e969452b801ddcfe5c9877deb88d5ad3/datacontract/export/sql_type_converter.py#L231

Timestamp is a valid duckdb type but as of yet there is no converter for it.

**Comment by RobertLD** [comment]
@jochenchrist Hey, I'd like your thoughts on this. This is currently a blocker for our project. I wanted to be sure I wasn't making a mistake.

The default duckdb convertion when reading a parquet does not account for timestamp types correctly it would appear.

```
      end_dtutc:
        $ref: "#/definitions/end_dtutc"
        required: true
        type: timestamp_ntz
```
![image](https://github.com/user-attachments/assets/9ed334a5-8e99-4d58-b351-0d157be7856d)

**Comment by jochenchrist** [comment]
what server type are you using?

**Comment by RobertLD** [comment]
> what server type are you using? S3 with parquet?

servers:
  local_data:
    type: local
    path: trading_strategies.parquet
    format: parquet


the file is read from duckdb, saved as parquet and then validated at a later step

**Comment by jochenchrist** [comment]
Looks like a bug. Do you have the possibility to reproduce this in a unit test and possibly create a PR to resolve the problem?

**Comment by RobertLD** [comment]
I'd be more than happy to

**Comment by RobertLD** [comment]
https://github.com/datacontract/datacontract-cli/pull/473 PR here

**Comment by RobertLD** [comment]
> > what server type are you using? S3 with parquet?
> 
> ```
> servers:
>   local_data:
>     type: local
>     path: trading_strategies.parquet
>     format: parquet
> ```
> 
> the file is read from duckdb, saved as parquet and then validated at a later step

PR here -> https://github.com/datacontract/datacontract-cli/pull/473

**Comment by jochenchrist** [comment]
resolved with #473

**Comment by RobertLD** [comment]
Thank you for picking up on this, been a busy week! Huge benefit for me
using the library with this fix inplace

**Comment by jochenchrist** [comment]
I just release `v0.10.14`

**Comment by RobertLD** [comment]
Awesome! In the meantime I'll see about getting import from parquet setup
