### ISSUE TITLE
When importing in dbt format, modify to import richer information.

### ISSUE THREAD

**Issue by syou6162** [datacontract/datacontract-cli#542]
The current `datacontract import --format dbt` only outputs simple information as a contract. It is only the column name / description / column type / tag.

- https://github.com/datacontract/datacontract-cli/blob/7d34626d673595294511464591705f92628a2e99/datacontract/imports/dbt_importer.py#L92-L96

However, dbt maintains rich information about columns, such as `relationships`, `primary_key`, and `not_null`, and this information should also be reflected in the contract.

**Comment by syou6162** [comment]
There is a lot of information that can be reflected in the contract from the dbt yaml, so it's a lot to give at once, but I plan to send pull requests for this issue in several parts!

**Comment by simonharrer** [comment]
Awesome. Looking forward to your help here!
