### ISSUE TITLE
[BUG] importing specific dbt-model generates contract for all models still

### ISSUE THREAD

**Issue by ksvedal-itmatter** [datacontract/datacontract-cli#550]
I can't post my full code here as I am working with a client but what I am trying to achieve is:
- Generate one data contract based on importing one specific dbt-model
- The overall goal is to explore whether using datacontract-cli with the import functionality can be used to generate contracts for existing data products (e.g. data models) at scale, to save time on manual work

**What I ran:**

```shell 
datacontract import --format dbt --source <my_local_manifest.json> --dbt-model <my_dbt_model> --output datacontract.yaml
```
**The result**
A datacontract.yaml with thousands of lines, not only for the selected / specific dbt-model but ALL models still.
This was not the expected result.

Thanks,
Kristian Svedal.

**Comment by simonharrer** [comment]
Thanks for reporting! 

Others stumbled upon this bug as well. It is already fixed in the main branch (see #532 ) and will be part of the next release. If you cannot wait for the next release, I recommend installing it from the main branch yourself.

**Comment by ksvedal-itmatter** [comment]
Great, thanks @simonharrer 👍

**Comment by ksvedal-itmatter** [comment]
@simonharrer  Is there a timeline / ETA for the next release? Thanks.
