### ISSUE TITLE
cannot escape reserved word on model

### ISSUE THREAD

**Issue by edsajorbe** [datacontract/datacontract-cli#557]
I have a model called Order (reserved word in SQL Server) and get error below:

`ERROR:soda.scan:[16:28:20] Query execution error in 3.sqlserver.Order.pkOrder.duplicate_count: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'Order'. (156) (SQLExecDirectW)")`

Is there any way to escape names? I've tried double quotes and brackets but no luck.
If cannot escape it, could you give me some advice on how to modify the code? I can try by myself.

Thanks.

**Comment by jochenchrist** [comment]
We have a similar issue with Postgres.

You could try to add `sqlserver` here:

https://github.com/datacontract/datacontract-cli/blob/main/datacontract/export/sodacl_converter.py#L35C5-L35C10

**Comment by jochenchrist** [comment]
Targeted with 0.10.17
